// <auto-generated />
namespace TaskDone_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserEmailAddedToProjectAndOffer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserEmailAddedToProjectAndOffer));
        
        string IMigrationMetadata.Id
        {
            get { return "202010290033578_UserEmailAddedToProjectAndOffer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
